### ISSUE TITLE
Dependency on aiobotocore renders packaging s3fs no longer possible

### ISSUE THREAD

**Issue by mgorny** [dask/s3fs#357]
I don't suppose there's anything that can be done about this. Nevertheless, I'd like to point out that due to dependency on aiobotocore we are no longer able to package new versions s3fs on Gentoo. FWICS the few other distributions that used to package s3fs are having the same problem.

The problem is that aiobotocore is a huge hack on internals of botocore, and therefore it requires very specific version of botocore. With the daily release cycle of botocore and rare releases of aiobotocore, we can't package it unless we repeatedly force old versions of botocore on our users.

**Comment by martindurant** [comment]
I am surprised! Indeed, I was aware that aiobotocore has very narrow dependency requirements on botocore, but for users who need it, isn't that a necessary and acceptable situation? I wouldn't have said that aiobotocore releases were rare, exactly ( https://github.com/aio-libs/aiobotocore/releases ).

**Comment by mgorny** [comment]
> Indeed, I was aware that aiobotocore has very narrow dependency requirements on botocore, but for users who need it, isn't that a necessary and acceptable situation?

Users who need aiobotocore are relatively small group compared to users who need botocore in general, and it would be unfair to block the latter to satisfy the former. Especially that it's not botocore's fault that someone chose to implement a huge hack against it.

> I wouldn't have said that aiobotocore releases were rare, exactly ( https://github.com/aio-libs/aiobotocore/releases ).

Depends on your definition of 'rare'. Compared to daily releases of botocore, they might be rare. But not even that is the problem.  The release from 4 days ago depends on botocore 1.17.44, i.e. the release from 18 days ago. That's 12 releases behind already, and it's going to grow.

**Comment by mrocklin** [comment]
Thank you for raising this issue @mgorny .  This is, as @martindurant says, both surprising and unfortunate.  I at least wasn't aware of the relationship between aiobotocore and botocore. 

I'm curious though, isn't this the kind of thing that a dependency solver should be able to handle?  I would expect aiobotocore to be pretty explicit about its requirements.  If someone wanted to install s3fs wouldn't the solver find a recent version of aiobotocore, then find the matching version of botocore and install those?  Or is the challenge that other packages also depend on very specific versions of `botocore`, and so it is hard to find a good global match?

**Comment by mgorny** [comment]
This depends on the system.

In case of Gentoo, we package every Nth version of botocore, and we just happened not to package the one aiobotocore needs. While I could package this one more version, these kind of dependencies are a maintenance nightmare. Since they're older than the newest one, they're given very little testing. I need to remember not to remove them when cleaning up old stuff because it'd break aiobotocore. Finally, I can't simultaneously have s3fs installed and test new versions of botocore.

PkgSrc, for example, does not support multiple versions at all.

**Comment by martindurant** [comment]
Obviously, I have no idea how to go about linux package management... *but* I thought I should point out that, according to https://pypistats.org/ , last month had 72M botocore downloads and 5M s3fs, so you may well find that aiobotocore will not be so niche any more ( see the graph [here](https://pypistats.org/packages/aiobotocore) ).

Of course, users have access to pip and conda too - system packages have different requirements.

**Comment by dwink** [comment]
This affects more than just OS packages -- the transitive dependency chain for basically anything that depends on boto3 is broken unless you can fully convert all packages to aiobotocore, or if the various pinned versions end up being compatible all the time.

For instance, I have a project that had s3fs 0.4.2 and boto3, and it wasn't pinned to 0.4.2 of s3fs; on Friday a minor code change went through CI and the entire project broke, because pip won't downgrade a package in order to satisfy a transitive dependency. So keeping up with s3fs means tracking aiobotocore releases and pinning/managing pinning of all boto3-based software that might be included in a project. Yikes.

**Comment by martindurant** [comment]
Sure - as I said, I don't know much about the constraints that you must be working under.
I would be surprised, though if this sort of situation were unusual. In practice, a large number of our users have conda and/or venv environments, so should be insluated.

**Comment by dwink** [comment]
I *have* a venv environment. This change broke it. That's what I'm trying to communicate here.

**Comment by martindurant** [comment]
So it's pip's fault... I'm not sure what to do about that. Presumably if you installed from scratch, you would get aiobotocore and botocore which match, and further installs would not update them. Conda's solver *will* downgrade packages to get a consistent environment.

**Comment by dwink** [comment]
> So it's pip's fault... I'm not sure what to do about that. Presumably if you installed from scratch, you would get aiobotocore and botocore which match, and further installs would not update them. Conda's solver _will_ downgrade packages to get a consistent environment.

The example above *was* installing from scratch. I created a new venv, installed just s3fs and boto3 and moto, and ended up with a broken setup.

I'll see what I can do to work around this, but I suspect this won't be nearly as isolated an issue as you seem to think, and at minimum I'd recommend explicitly documenting that in order to use s3fs going forward, users will need to curate all their dependencies on aiobotocore's release cadence.

**Comment by TomAugspurger** [comment]
Pip's new dependency resolver is for case like this.

```console
$ pip install s3fs boto3 mock --use-feature=2020-resolver
...
Successfully installed aiobotocore-1.1.1 aiohttp-3.6.2 aioitertools-0.7.0
async-timeout-3.0.1 attrs-20.2.0 boto3-1.14.44 botocore-1.17.44
chardet-3.0.4 docutils-0.15.2 fsspec-0.8.0 idna-2.10 jmespath-0.10.0
mock-4.0.2 multidict-4.7.6 python-dateutil-2.8.1 s3fs-0.5.0
s3transfer-0.3.3 six-1.15.0 typing-extensions-3.7.4.3 urllib3-1.25.10
wrapt-1.12.1 yarl-1.5.1
```

**Comment by graingert** [comment]
`aiobotocore[boto3]` is supposed to fix it

**Comment by dwink** [comment]
> there's an extra; `aiobotocore[boto3]` which is supposed to fix this

Which is great -- except I don't depend on aiobotocore except transitively through THIS package. So I have to know about this dependency and manage it (and hopefully this package doesn't depend on anything that isn't in the botocore version aiobotocore[boto3] provides). I know this is a weakness of the Python ecosystem but it's a really frustrating one.

**Comment by graingert** [comment]
I could try adding and `s3fs[boto3]` extra that selects `aiobotocore[boto3]`

**Comment by dwink** [comment]
> I could try adding an `s3fs[boto3]` extra that selects `aiobotocore[boto3]`

That sounds like it might be perfect.

**Comment by martindurant** [comment]
(note that s3fs doesn't actually depend on boto3, but these all seem to be intermingled)

**Comment by mrocklin** [comment]
@jakirkham you may also find this issue interesting with your packaging hat
on

**Comment by jakirkham** [comment]
I don't spend that much time with `pip`. So doubt I'm much help here.

**Comment by graingert** [comment]
I think you have to specify the boto3 and awscli directly as they are in aiobotocore and bump them each time there's a release

**Comment by caseyhartnett** [comment]
Blocking our build when transitioning from 3.7 python to 3.8 pythons. Include s3fs and it fails otherwise build completes.

**Comment by graingert** [comment]
@caseyhartnett pinning both boto3 and botocore seems the best option here. Otherwise use the `--use-feature=2020-resolver` flag

**Comment by shughes-uk** [comment]
I have a long back and forth with one of the aiobotocore devs over this https://github.com/aio-libs/aiobotocore/issues/829#issuecomment-702936507 , might be helpful to have more people weigh in. I think the only solution they have on their end is to vendorize botocore, which I understand them being reluctant to do as it's a pain in the butt.

**Comment by CloudySnake** [comment]
Sorry if this has been asked already, but why does s3fs have this dependency on aiobotocore? I have the same issue with versioning (and also Moto now doesn't play nicely with s3fs due to the async additions) - as a workaround I have pinned s3fs to v0.4.* but that's not a permanent solution.

**Comment by jmahlik** [comment]
> Sorry if this has been asked already, but why does s3fs have this dependency on aiobotocore? I have the same issue with versioning (and also Moto now doesn't play nicely with s3fs due to the async additions) - as a workaround I have pinned s3fs to v0.4.* but that's not a permanent solution.

How hard might it be to refactor to use boto directly? I might be willing to look in to this unless there's some specific reasons it would not work. Briefly glancing, it seems possible?

**Comment by graingert** [comment]
This is because boto and botoxore do not support asyncio

**Comment by thehesiod** [comment]
Another option is vendoring aioboto and it's deps, or install it in its own sub venv

**Comment by graingert** [comment]
pip 20.3 released with the 2020-resolver enabled by default

**Comment by Downchuck** [comment]
Ran into this in a few different ways -- aiobotocore does force one specific version of boto3, and as such the extra aiobotocore[boto3] needs to be explicit, it seems quite often, so things materialize.

Pipfile:
```
aiobotocore = {extras = ["boto3"], version = "*"}
s3fs = "*"
```

In that package (with setup.py containing), I still wound up needing another explicit reference for Pipenv:
```
django-storages = {extras = ["boto3"], version = "*"}
aiobotocore = {extras = ["boto3"], version = "*"}
```

**Comment by graingert** [comment]
@Downchuck did you try this with pip 20.3?

**Comment by crypdick** [comment]
This change has broken our CI hooks, which use [jazzband/pip-tools](https://github.com/jazzband/pip-tools/). Related issue:  https://github.com/jazzband/pip-tools/issues/1190

**Comment by thehesiod** [comment]
> This change has broken our CI hooks, which use [jazzband/pip-tools](https://github.com/jazzband/pip-tools/). Related issue: [jazzband/pip-tools#1190](https://github.com/jazzband/pip-tools/issues/1190)

what change broke which CI hooks in what way?

**Comment by crypdick** [comment]
@thehesiod Sorry, I'll elaborate: our setup fails at `pip-compile requirements.in` with the error:

```
Could not find a version that matches botocore<1.19.53,<1.20.0,==1.19.54,>=1.19.52,>=1.19.54 (from aiobotocore[boto3]==1.2.0->-r src/requirements.in (line 5))
Tried: <several hundred versions>

There are incompatible versions in the resolved dependencies:
  botocore<1.19.53,>=1.19.52 (from aiobotocore[boto3]==1.2.0->-r src/requirements.in (line 5))
  botocore<1.20.0,>=1.19.54 (from boto3==1.16.54->-r src/requirements.in (line 8))
  botocore==1.19.54 (from awscli==1.18.214->-r src/requirements.in (line 4))
  ```
  
 However, `pip install -r src/requirements.in` works fine (pip==20.3.3). These are the relevant lines in requirements.in:
 ```
 awscli
 aiobotocore[boto3]  # added as per this issue
 boto3
 dask
 pip-tools==5.4.0
 s3fs[boto3]  # [boto3] extra added as per this issue
 ```

**Comment by thehesiod** [comment]
per the above you depend not only on boto3 but also awscli, so you need to only add this requirement:
`aiobotocore[awscli,boto3]`

**Comment by crypdick** [comment]
@thehesiod I modified that line to `aiobotocore[awscli,boto3]`, getting similar output:

```
WARNING: s3fs 0.5.2 does not provide the extra 'boto3'
Could not find a version that matches botocore<1.19.53,<1.20.0,==1.19.56,>=1.19.52,>=1.19.56 (from boto3==1.16.56->-r src/requirements.in (line 8))
Tried: <many options>
There are incompatible versions in the resolved dependencies:
  botocore==1.19.56 (from awscli==1.18.216->-r src/requirements.in (line 4))
  botocore<1.20.0,>=1.19.56 (from boto3==1.16.56->-r src/requirements.in (line 8))
  botocore<1.19.53,>=1.19.52 (from aiobotocore[awscli,boto3]==1.2.0->-r src/requirements.in (line 5))
```

**Comment by thehesiod** [comment]
You then need to remove awscli + boto3 from requirements as they now come from aiobotocore

**Comment by crypdick** [comment]
@thehesiod tyvm!! That worked :)

**Comment by bra-fsn** [comment]
I've just skimmed over the above discussion, so I may be missing something, but why do you need the `aiobotocore` dependency in the first place?
As far as I can understand the issue, most of the users don't want `aiobotocore` dependency (as it will need a pinned `boto3` and `botocore` dependency as well), but want to leave it out completely.
So the solution would be to make an `async` or `aiobotocore` extra for `s3fs`, which pulls in `aiobotocore`, but otherwise it doesn't depend on it.
This could be as easy to wrap the `aiobotocore` import into a try-except block and move the `aiobotocore` dependency to an extra, no?

**Comment by shlomiken** [comment]
> I suspect many people will continue hitting this frustrating version conflict now that pip will explicitly fail install unless you force it back to the old resolver.
> 
> > Another option is vendoring aioboto and it's deps, or install it in its own sub venv
> 
> Is there any chance of either of these things becoming a reality? For us, it seems odd to force older versions of primary packages (awscli and boto3) due to a secondary package's obscure dependency chain. We'd like to continue using s3fs but will have to eventually refactor away from it if this isn't something that will be addressed.

Unfortunately - this is exactly what we are doing , refactor away to use only boto3. this has been a nightmare for more than 6 months now. not acceptable to use old-resolver, cmon guys , we have CI-CD systems we don't want to refactor everything to support an old resolver.

**Comment by graingert** [comment]
@shlomiken @bsplosion hello! Installing s3fs and boto3/awscli should "just work" with the 2020-resolver in pip 21.0.1

however for pip-compile from pip-tools is still waiting on support for https://github.com/jazzband/pip-tools/issues/1298

but you can work around it with:
```in
s3fs
aiobotocore[awscli,boto3]
```

**Comment by shlomiken** [comment]
@graingert - thanks for the reply , unfortunately i see many of these in my pip install command.
```
WARNING: aiobotocore 0.3.0 does not provide the extra 'awscli'
```

**Comment by CalebEverett** [comment]
What is the recommended way to install these packages together?

```yaml
s3fs = "*"
moto = "*"
boto3 = "*"
```

**Comment by graingert** [comment]
`pip install s3fs[boto3] moto`

**Comment by CalebEverett** [comment]
I still get incompatible versions using trying that with pipenv.

```
  botocore<1.20.50,>=1.20.49 (from aiobotocore==1.3.0->s3fs[boto3]==2021.4.0->-r /tmp/pipenvnk225cejrequirements/pipenv-upj0zg8x-constraints.txt (line 3))
  botocore<1.21.0,>=1.20.57 (from boto3==1.17.57->moto==2.0.5->-r /tmp/pipenvnk225cejrequirements/pipenv-upj0zg8x-constraints.txt (line 6))
  botocore>=1.12.201 (from moto==2.0.5->-r /tmp/pipenvnk225cejrequirements/pipenv-upj0zg8x-constraints.txt (line 6))
```

**Comment by damonmaria** [comment]
@CalebEverett Have you tried using Pipenv with `SYSTEM_VERSION_COMPAT=1`. That will use the newer Pip resolver. I haven't tried it specifically with `s3fs`.

**Comment by CalebEverett** [comment]
@damonmaria thanks, but no such luck - it still complains about incompatible versions without specifying s3fs<0.5.0

**Comment by theholy7** [comment]
@CalebEverett 
what we did was:
```
aiobotocore[boto3]
s3fs~=0.4.0
```
Does that work for you?

**Comment by CalebEverett** [comment]
@theholy7 thanks - yes, not sure if I ended up with 0.4.0 exactly, but found that <0.5.0 works.

**Comment by tinkerware** [comment]
For anyone who ended up in this issue while trying to get `moto`, `s3fs` and `aiobotocore` together, this is what I currently use for the most recent releases of these dependencies in `Pipenv`:

```ini
[dev-packages]
moto = "~= 2.0"

[packages]
# The two dependencies below should be kept together, since they solve a thorny
# transitive dependency problem documented at https://github.com/dask/s3fs/issues/357.
s3fs = {version = "~=2021.4", extras = ["boto3"]}
aiobotocore = {version = "*", extras = ["boto3"]}
```

**Comment by dazza-codes** [comment]
This kind of issue was anticipated in https://github.com/aio-libs/aiobotocore/issues/862

It would be ideal if this were resolved by relaxing boto* version dependencies in aiobotocore, but a PR to do so was not merged.  I was compelled to publish a fork in https://pypi.org/project/aio-botocore/
- but that doesn't solve the s3fs dependency problem for anyone using s3fs > 0.4.x, unless s3fs were to switch to the forked version of aio-botocore or the upstream aiobotocore were to merge https://github.com/aio-libs/aiobotocore/pull/834 (or an update to that effect)

**Comment by tuky** [comment]
this pipfile works for us now together with `SYSTEM_VERSION_COMPAT=1`:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
aiobotocore = {version = "*", extras = ["boto3"]}
s3fs = "*"
django-storages = "*"
```

we also had to make sure, that we have neither `boto3` nor `botocore` listed explicitly in our pipfile, although we are using it directly ourselves.

**Comment by martindurant** [comment]
> ZIP based lambdas

Sorry, I'm don't know what you mean. Maybe you can describe your workflow more thoroughly?

**Comment by jmahlik** [comment]
Sorry, I've been following this issue for five years now, it just gave me a notification. Thought I'd chime in. The deps haven't broken things in about three years, so that's some excellent work by the maintainers IMO.

That being said, trying to install all those deps on lambda is only going to lead to heartache. I know this doesn't solve the problem but can I ask the use case?

`python -X importtime <your file>` <-- paying for 10 seconds right there

**Comment by martindurant** [comment]
I will look into it - I'm sure there will be a working combination. Part of the problem is, that botocore releases so often and resolvers avoid being many versions back (they don't look at the date of release).

I will mention, that the bytes limit on lambda is one of the reasons for the continued existence of fastparquet, which is much smaller than pyarrow. This reason will go away when pandas explicitly depends on pyarrow in v3; and already there is some functionality/optimisation only available via arrow.

**Comment by hb2638** [comment]
> I will look into it - I'm sure there will be a working combination. Part of the problem is, that botocore releases so often and resolvers avoid being many versions back (they don't look at the date of release).
> 
> I will mention, that the bytes limit on lambda is one of the reasons for the continued existence of fastparquet, which is much smaller than pyarrow. This reason will go away when pandas explicitly depends on pyarrow in v3; and already there is some functionality/optimisation only available via arrow.

Thank you. I'm hopeful that sometime in the near feature, they'll bump the lambda payload size. They suprisingly increased the size of SQS messages to 1MB and API gateway timeouts can now go has high as 5 minutes. We're are aware of fastparquet and our lambda/code supports it. We need pyarrow to handle some stuff we do with glue and athena. There was some functionality that didn't exist in parquet when we compared them a few years ago. I believe one of them was consolidating multiple parquet files to a single file. I think another was "streaming" data into a parquet file to reduce memory overhead. I forgot the other edge cases but those were the two big ones.
